"""Move some columns

Revision ID: 34510d09d3d9
Revises: 83ebfbc718c8
Create Date: 2023-04-20 18:10:33.386513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34510d09d3d9'
down_revision = '83ebfbc718c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repertoire', schema=None) as batch_op:
        batch_op.add_column(sa.Column('knowledge', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('started_learning', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_played', sa.DateTime(), nullable=True))

    with op.batch_alter_table('tunes', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('started_learning')
        batch_op.drop_column('knowledge')
        batch_op.drop_column('last_played')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tunes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_played', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('knowledge', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('started_learning', sa.DATETIME(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('repertoire', schema=None) as batch_op:
        batch_op.drop_column('last_played')
        batch_op.drop_column('started_learning')
        batch_op.drop_column('knowledge')

    # ### end Alembic commands ###
