"""user_tune extra columns

Revision ID: 34958f2d72f9
Revises: 452cea8d6119
Create Date: 2023-04-23 15:23:53.462308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34958f2d72f9'
down_revision = '452cea8d6119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tune', schema=None) as batch_op:
        batch_op.add_column(sa.Column('knowledge', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('started_learning', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_played', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tune', schema=None) as batch_op:
        batch_op.drop_column('last_played')
        batch_op.drop_column('started_learning')
        batch_op.drop_column('knowledge')

    # ### end Alembic commands ###
