"""user_tune

Revision ID: 452cea8d6119
Revises: ff5100eb6ed5
Create Date: 2023-04-23 15:22:17.861106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452cea8d6119'
down_revision = 'ff5100eb6ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_tune',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tune_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tune_id'], ['tunes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tune_id')
    )
    op.drop_table('repertoire')
    with op.batch_alter_table('tunes', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('started_learning')
        batch_op.drop_column('last_played')
        batch_op.drop_column('knowledge')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('tunes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('knowledge', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('last_played', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('started_learning', sa.DATETIME(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    op.create_table('repertoire',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('tune_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['tune_id'], ['tunes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tune_id')
    )
    op.drop_table('user_tune')
    # ### end Alembic commands ###
