"""Decade as column_property

Revision ID: 9fd8666d311a
Revises: c66d2f030339
Create Date: 2023-04-26 00:56:11.991484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fd8666d311a'
down_revision = 'c66d2f030339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tunes', schema=None) as batch_op:
        batch_op.drop_column('decade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tunes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decade', sa.VARCHAR(length=5), nullable=True))

    # ### end Alembic commands ###
