"""empty message

Revision ID: c66d2f030339
Revises: 34958f2d72f9
Create Date: 2023-04-23 22:57:04.298775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66d2f030339'
down_revision = '34958f2d72f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tunes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groups', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tunes', schema=None) as batch_op:
        batch_op.drop_column('groups')

    # ### end Alembic commands ###
