"""Alter join table

Revision ID: ff5100eb6ed5
Revises: 34510d09d3d9
Create Date: 2023-04-20 22:59:06.256587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5100eb6ed5'
down_revision = '34510d09d3d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tune',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('composer', sa.String(length=64), nullable=True),
    sa.Column('key', sa.String(length=3), nullable=True),
    sa.Column('other_key', sa.String(length=12), nullable=True),
    sa.Column('song_form', sa.String(length=20), nullable=True),
    sa.Column('style', sa.String(length=20), nullable=True),
    sa.Column('meter', sa.SmallInteger(), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('decade', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('user_tune',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tune_id', sa.Integer(), nullable=False),
    sa.Column('knowledge', sa.String(length=10), nullable=True),
    sa.Column('started_learning', sa.DateTime(), nullable=True),
    sa.Column('last_played', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tune_id'], ['tune.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tune_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.drop_index('ix_users_username')

    op.drop_table('users')
    op.drop_table('tunes')
    op.drop_table('repertoire')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repertoire',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('tune_id', sa.INTEGER(), nullable=False),
    sa.Column('knowledge', sa.VARCHAR(length=10), nullable=True),
    sa.Column('started_learning', sa.DATETIME(), nullable=True),
    sa.Column('last_played', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tune_id'], ['tunes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'tune_id')
    )
    op.create_table('tunes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), nullable=False),
    sa.Column('composer', sa.VARCHAR(length=64), nullable=True),
    sa.Column('key', sa.VARCHAR(length=3), nullable=True),
    sa.Column('other_key', sa.VARCHAR(length=12), nullable=True),
    sa.Column('song_form', sa.VARCHAR(length=20), nullable=True),
    sa.Column('style', sa.VARCHAR(length=20), nullable=True),
    sa.Column('meter', sa.SMALLINT(), nullable=True),
    sa.Column('year', sa.SMALLINT(), nullable=True),
    sa.Column('decade', sa.VARCHAR(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_username', ['username'], unique=False)
        batch_op.create_index('ix_users_email', ['email'], unique=False)

    op.drop_table('user_tune')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('tune')
    # ### end Alembic commands ###
